package com.nativemoduledemo

import android.os.Build
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule

// NativeAppDeviceInfoSpec is auto-generated by Codegen
@ReactModule(name = DeviceInfoModule.NAME)
class DeviceInfoModule(reactContext: ReactApplicationContext) :
    NativeAppDeviceInfoSpec(reactContext) {

    companion object {
        const val NAME = "DeviceInfoModule"
    }

    override fun getName() = NAME

    override fun getDeviceInfo(promise: Promise) {
        try {
            val map = Arguments.createMap().apply {
                putString("deviceName",    Build.MODEL)
                putString("systemName",    "Android")
                putString("systemVersion", Build.VERSION.RELEASE)
                putString("model",         "${Build.MANUFACTURER} ${Build.MODEL}")
            }
            promise.resolve(map)
        } catch (e: Exception) {
            promise.reject("DEVICE_INFO_ERROR", e.message, e)
        }
    }
}
